"""inbox approvals

Revision ID: c0aaffb677db
Revises: b8cc6d36d4d3
Create Date: 2026-10-08 19:42:13.257974

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0aaffb677db"
down_revision: str | Sequence[str] | None = "b8cc6d36d4d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbox_items",
        sa.Column("kind", sa.String(length=20), server_default="question", nullable=False),
    )
    op.add_column("inbox_items", sa.Column("preview_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbox_items", "preview_url")
    op.drop_column("inbox_items", "kind")
    # ### end Alembic commands ###
