"""create inbox items

Revision ID: 4db27901744e
Revises: cabf8f61b148
Create Date: 2026-10-08 02:05:20.608208

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from staffroom_api.db.rls import disable_tenant_rls, enable_tenant_rls

# revision identifiers, used by Alembic.
revision: str = "4db27901744e"
down_revision: str | Sequence[str] | None = "cabf8f61b148"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_items",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.String(length=100), nullable=False),
        sa.Column("employee", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_inbox_items_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inbox_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_items")),
        sa.UniqueConstraint("run_id", "question_id", name=op.f("uq_inbox_items_run_id")),
    )
    op.create_index(op.f("ix_inbox_items_run_id"), "inbox_items", ["run_id"], unique=False)
    op.create_index(op.f("ix_inbox_items_tenant_id"), "inbox_items", ["tenant_id"], unique=False)
    # ### end Alembic commands ###
    for sql in enable_tenant_rls("inbox_items"):
        op.execute(sql)


def downgrade() -> None:
    """Downgrade schema."""
    for sql in disable_tenant_rls("inbox_items"):
        op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbox_items_tenant_id"), table_name="inbox_items")
    op.drop_index(op.f("ix_inbox_items_run_id"), table_name="inbox_items")
    op.drop_table("inbox_items")
    # ### end Alembic commands ###
