"""inbox secret name

Revision ID: b8cc6d36d4d3
Revises: 4db27901744e
Create Date: 2026-10-08 19:23:40.813596

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8cc6d36d4d3"
down_revision: str | Sequence[str] | None = "4db27901744e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inbox_items", sa.Column("secret_name", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbox_items", "secret_name")
    # ### end Alembic commands ###
